Unleash/unleash-edge

server/src/data_sources/mod.rs
server/src/data_sources/redis_provider.rs
server/src/error.rs
server/src/frontend_api.rs
server/src/main.rs
server/src/tls.rs
server/tests/redis_test.rs

Fixes small formatting / styling issues to make the pre-commit hook happy again.

style: fix formatting

---

README.md
server/src/cli.rs

Small README fixes and update.

docs: update README

---

Cargo.lock
server/Cargo.toml
server/src/error.rs
server/src/lib.rs
server/src/main.rs
server/src/types.rs
server/src/unleash_client.rs
server/src/urls.rs

Building a client to get upstream data and post metrics upstream

feat: add client for getting features

---

README.md

A small section on benchmarking added, I feel like this needs more fleshing out, but at least it adds some initial numbers.

task: Document initial benchmarks

---

README.md

This expands on the README file to explain what Edge is, why it's useful and expands on the differences between this and the Unleash Proxy
The README here gets built into our main documentation, so having an explanation on what it is and why it's useful is important

docs: update readme to explain what edge is and why its useful

---

.github/workflows/add-to-project.yml

This is to keep track of this project under GH Watcher watch https://github.com/orgs/Unleash/projects/8/

chore: this GH action will report PRs and issues

---

development-guide.md

Also adds a couple of extra common commands to be more welcoming

docs: Update development guide with note about docker

---

.github/workflows/build-docker-release.yaml
.github/workflows/build-main-docker-tag.yaml

Switching to new ecr publish role that is managed by code.

chore: switch docker publish role

---

.github/workflows/build-debug-docker-release.yaml
.github/workflows/build-main-debug-docker-container.yaml
Dockerfile.debug

This adds a docker image that has some tools in it, the intent of this is to make it easier to debug edge.

feat: docker debug container

---

.github/workflows/build-debug-docker-release.yaml
.github/workflows/build-main-debug-docker-container.yaml
Dockerfile.debug

fix: we require libssl3 in the debug container

---

proxyclienttest/index.html

It just corrects the proxyclienttest/index.html indent.

style: proxyclienttest: correct index.html indent

---

.github/workflows/release.yml
Cargo.toml

Finally upgraded upload and download artifact to v4 with hopefully the correct config.

Updated cargo dist to 0.9.0

---

server/src/internal_backstage.rs

Adds an endpoint /internal-backstage/features displaying which features we store per cache key

feat: internal backstage features endpoint

---

server/src/builder.rs
server/src/persistence/redis.rs

This removes passwords from the logs

feat(redis): don't log redis password

---

.dockerignore
.github/workflows/build-docker-with-chef.yaml
Dockerfile.chef

An attempt at speeding up our build, and moving to newer build platforms so we can use openssl v3

chore: Added a workflow/docker file using chef instead of cross

---

.github/notify_pipeline.sh

For more context look at https://linear.app/unleash/project/sre-move-pipeline-to-platform-cluster-5cca775c3011/overview

chore: move pipeline to platform.getunleash.io

---

README.md
server/README.md

Readme: Add an example for a docker command to illustrate what an upstream URL looks like

Add example docker command

---

server/src/http/broadcaster.rs
server/src/prom_metrics.rs

Added a single label here (environment).
Do we need anything else?

task: added gauge for showing number of streaming clients connected

---

server/src/http/unleash_client.rs

Verifying that connection-id and interval headers are sent. Modified existing custom headers test to make it more generic. If you'd prefer a separate test please let me know
Also looks like formatter has change a few lines.

test: identification headers

---

Cargo.lock
server/Cargo.toml

fix(deps): zip 2.5.0 is not semver with 2.2.3~2.4.2 

---

server/src/metrics/actix_web_prometheus_metrics.rs

fix: track path for 304/NOT_MODIFIED

---

server/src/cli.rs

fix: make cors arguments global

---

Cargo.lock
server/Cargo.toml
server/src/client_api.rs
server/src/http/background_send_metrics.rs
server/src/metrics/client_impact_metrics.rs
server/src/metrics/client_metrics.rs
server/src/metrics/mod.rs
server/src/types.rs

- `ImpactMetric` and`ImpactMetricEnv` were added to our types project
- `MetricsBatch` and `BatchMetricsRequestBody` include the `impact_metrics` field (batch metrics ignore impact metrics for now)
- `MetricsCache` stores impact metrics in a `DashMap` keyed by app name and environment using the `ImpactMetricsKey` structure. I'm considering adding metric name to the key if needed
- The `sink_impact_metrics` method properly aggregates metrics by name and handles different metric types:
- For counters, it sums values for samples with the same labels
- For gauges, it keeps the last value for each set of labels
- The `merge_impact_metrics` method correctly merges metrics from different apps
- Impact metrics are handled in `register_client_metrics` with conversion to `ImpactMetricEnv`
- Labels …

feat: impact metrics

---

server/src/metrics/client_metrics.rs

When we were merging the samples some other part of the code was not removing enough items from the cache.

fix: stop merging samples for impact metrics

---

crates/unleash-edge-appstate/src/lib.rs
crates/unleash-edge-auth/src/token_validator.rs
crates/unleash-edge-backstage/src/lib.rs
crates/unleash-edge-client-api/src/delta.rs
crates/unleash-edge-client-api/src/features.rs
crates/unleash-edge-feature-refresh/src/delta_refresh.rs
crates/unleash-edge-feature-refresh/src/lib.rs
crates/unleash-edge-integration-tests/src/delta_refresher.rs
crates/unleash-edge/src/edge_builder.rs
crates/unleash-edge/src/lib.rs

Splits the responsibilities for FeatureRefresher and DeltaRefresher into two separate structs + impls

chore: cleanup refresher

---

Cargo.lock
Cargo.toml
crates/unleash-edge-client-api/src/metrics.rs
crates/unleash-edge-metrics/src/client_impact_metrics.rs
crates/unleash-edge-metrics/src/metric_batching.rs

* Updated unleash-types-rs with histogram support but also breaking changes in the impact metrics API to make impossible states impossible
* Improved test quality (split big test into smaller ones, removed find operations from tests, consistent testing patterns to better express intent and avoid irrelevant details)

feat: impact metrics histogram

---

Cargo.lock
Cargo.toml
crates/unleash-edge-http-client/src/lib.rs
crates/unleash-edge/Cargo.toml
crates/unleash-edge/src/main.rs

Actix aggressively reaps passive connections, axum does not by default. This tries to set timeouts on the socket, both TCP and HTTP

fix(socket): Setup slow loris protection.
