Unleash/unleash-edge

- Cargo.lock
- server/Cargo.toml
- server/src/main.rs
Since we know we'll probably be used from browsers, setting the CORS headers are a must.
> feat: Added cors middleware

- server/src/cli.rs
- server/src/main.rs
This code moves from value enum to subcommands, keeping arguments for http setup, but allowing you to only have to worry about configuring the mode you want to launch edge in.
The value here is harder to see, since we still only have one subcommand. Judging from our experience in the node version here, where we ended up with a rather complicated yaml config, this is pre-optimising a bit to ease the extension into more modes later.
> feat: use subcommands rather than valueenum

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/offline_provider.rs
- server/src/types.rs
Adds a basic implementation of front end endpoints. The core purpose of this PR is to consume Yggdrasil and set a path forward for integration testing
> feat: add basic proxy endpoints and related test code

- server/src/main.rs
Seems to be a bug in the Cors crate, according to this: https://stackoverflow.com/questions/74867363/actix-cannot-start-server-service-0
This makes the server run without crashing
> fix: patch the way CORS headers are done

- server/src/cli.rs
- server/src/metrics.rs
Building on our BuildInfo endpoint, this adds a couple of nice labels to all our prometheus metrics, allowing us to filter on versions of edge what's working/not working.
> task: Added prometheus metrics from shadow

- Cargo.lock
- server/Cargo.toml
- server/src/main.rs
So, to save our clients more computation, this PR adds an ETag middleware, which will calculate the hash of the body of responses to GET requests.
It uses https://github.com/chriswk/actix-middleware-etag for now
Future improvement particularly for the /api/client/features endpoint might be to use the fact that our hash is a lot more static, since we know when we update our content, we could use that to calculate the hash when refreshing.
I'm not advanced enough to know how to get that to work for now. I ended up fighting the type system and our expectations for what a middleware should do, so this is a nice compromise. If anyone feels like we're too slow/paying too much cpu to calculate the responses, we could revisit this in the future.
> task: added etag middleware

- Dockerfile
This PR updates our Dockerfile to take advantage of our musl build, and just use scratch as BASE, which means that the only thing that exists in the container is our executable. Smaller image, smaller attack surface. :)
> task: Build minimal docker container from scratch base

- Cargo.lock
- README.md
- development-guide.md
- server/Cargo.toml
- server/src/cli.rs
- server/src/client_api.rs
- server/src/data_sources/mod.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/edge_api.rs
- server/src/error.rs
- server/src/frontend_api.rs
- server/src/internal_backstage.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/metrics.rs
- server/src/tls.rs
- server/src/types.rs
- server/tests/redis_test.rs
Refactors the way we create and handle data sources i.e. we pass the parent trait around rather than passing the struct. On the backbone of that, this adds a Redis datasource and introduces test containers so that we can get useful tests around data source implementations
> Implement redis datasource

- server/src/types.rs
- server/src/unleash_client.rs
Slight refactoring and mocks token validation on the test server.
> test: slight refactor and mock token validation

- server/src/main.rs
Allows everything on the CORS middleware so we can test Edge with a frontend SDK for now.
> fix: allow any on CORS

- server/src/frontend_api.rs
- server/src/http/background_refresh.rs
- server/src/main.rs
Previously our spin loop slept for 15 seconds and then hit the await on the channel for a new token to validate.
This PR changes that to use tokio::select to either refresh features for known tokens each 10th second, or receive a new token to validate.
Should allow us to use more than one token and get them refreshed
> fix: features get refreshed.

- server/src/http/background_refresh.rs
having thought about this over the weekend this PR includes two optimizations. One for sending on the validated_tokens from the validate token channel. One for filtering which tokens the feature_refresh_channel keeps on TokenType. Should prevent us from receiving 403's from Upstream.
Also pointed out to me that our auth middleware also needs to check the tokentype before allowing/disallowing the call.
> task: Updated to only refresh tokens of type Client

- server/src/data_sources/memory_provider.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/frontend_api.rs
- server/src/middleware/validate_token.rs
- server/src/types.rs
- server/tests/redis_test.rs
There's one test failing here, because I haven't had time to fix the redisprovider defaulting to unknown for validationstatus (seems correct, we just need to mock that it is validated)
> feat: switch to backing with HashMap<token, EdgeToken>

- server/src/client_api.rs
- server/src/data_sources/builder.rs
- server/src/data_sources/memory_provider.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/data_sources/repository.rs
- server/src/frontend_api.rs
- server/src/http/background_refresh.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/middleware/validate_token.rs
- server/src/types.rs
- server/tests/redis_test.rs
Reworks the source/sink architecture to be truly independent of each other. This means that stores for offline mode no longer need to implement the sink API, which makes no sense in that context
> chore: redesign source/sink architecture

- server/src/client_api.rs
- server/src/edge_api.rs
- server/src/error.rs
- server/src/http/background_send_metrics.rs
- server/src/http/unleash_client.rs
- server/src/metrics/client_metrics.rs
- server/src/types.rs
My naïve implementation of client metrics with a flatter structure - Instead of storing buckets in the metrics cache and converting back and forth, we store them as ClientMetricsEnv. Also uses a `MetricsKey` as that hash key, based on `app_name` and `toggle_name` to identify each `ClientMetricsEnv`.
> task: implement client metrics

- server/src/cli.rs
- server/src/data_sources/builder.rs
- server/src/data_sources/memory_provider.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/edge_api.rs
- server/src/frontend_api.rs
- server/src/http/background_send_metrics.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/types.rs
Add `send_metrics_task` to our running tasks. It accepts a new arg: `metrics_interval_seconds`.
Rename `get_valid_tokens` to `filter_valid_tokens` to better reflect its behaviour. Add `get_valid_tokens` to return all valid tokens from our store.
Implement `background_send_metrics`.
> task: client metrics start task

- Cargo.lock
- server/Cargo.toml
- server/src/data_sources/memory_provider.rs
- server/src/data_sources/mod.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/frontend_api.rs
- server/src/types.rs
- server/tests/redis_test.rs
This redesigns the way we store data in the memory and Redis providers to store incoming features by environment rather the token string. This means that incoming features for an environment will be merged in the case that the come from the same environment but different tokens. To handle this in the sources, outgoing data is filtered by project
> chore: redesign source and sinks to store features

- server/src/auth/mod.rs
- server/src/auth/token_validator.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/data_sources/builder.rs
- server/src/data_sources/memory_provider.rs
- server/src/data_sources/offline_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/edge_api.rs
- server/src/frontend_api.rs
- server/src/http/background_refresh.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/middleware/validate_token.rs
- server/src/types.rs
- server/tests/redis_test.rs
- Adds the token validator concept so we can properly handle token validation wherever we need to;
- Fetches data for validated tokens;
- Allows setting client keys through arg so we can pre-warm;
- Misc fixes and other improvements and refactors;
> task: token validator

- server/src/data_sources/memory_provider.rs
This collapses the keys seen. Removing keys that have been subsumed by a wider key (a key that includes the same projects or more as existing keys).
> task: Subsume keys to check

- server/src/data_sources/memory_provider.rs
Client features were being read on update, correctly calculated and then subsequently discarded. This patch makes incoming features actually get written to the memory provider
> fix: an issue where client features wouldn't correctly update

- Cargo.lock
- README.md
- server/Cargo.toml
- server/src/cli.rs
- server/src/main.rs
So, since some of our users might not want edge to start up a thread on each physical CPU they have available, this PR makes the number of workers configurable as an environment parameter as well as a CLI argument. 
This allows a less resource hungry deployment of Edge for local development.
> feat: allow controlling http server workers spun up

- server/src/main.rs
- server/src/types.rs
So, our FromRequest for EdgeToken was failing for offline mode now that we had changed our try_from to only allow tokens following the UnleashToken spec to actually parse successfully, thus 403'ing all requests against an unleash server in offline mode. This fixes that so that offline mode again supports users using secret123 as their token if they so desire.
> fix: Make offline mode handle non-Unleash tokens as valid secrets

- .github/workflows/build-docker-release.yaml
- .github/workflows/docker_ecr_arch64.yaml
- Dockerfile
- Dockerfile.publish
- Dockerfile.x86_64
Performance with musl images was awful. This PR changes to use distroless and makes our builds build for -gnu instead of -musl
- Use non-root user, I have a template for how to do it, but this PR just moves us to distroless for now
> fix: Move to distroless with libc

- .github/workflows/build-docker-release.yaml
Since we're prefixing tags with unleash-edge-, metadata-action's semver type fails to work on our released tags. This PR changes to using patterns for creating the {{ version }} and {{ major.minor }} tags.
> task: updated workflow to use regex

- server/src/auth/token_validator.rs
- server/src/data_sources/builder.rs
- server/src/data_sources/memory_provider.rs
- server/src/data_sources/redis_provider.rs
- server/src/data_sources/repository.rs
- server/src/metrics/client_metrics.rs
- server/src/middleware/validate_token.rs
- server/tests/redis_test.rs
This swaps out the underlying locks in the memory and Redis providers. Instead we use a DashMap, which holds internal locking primitives instead. This in turn means that we remove the lock contention issues when resolving features
> chore: removal of RW locks for dashmaps

- server/src/client_api.rs
- server/src/data_sources/builder.rs
- server/src/edge_api.rs
- server/src/frontend_api.rs
- server/src/http/background_refresh.rs
- server/src/http/background_send_metrics.rs
- server/src/internal_backstage.rs
- server/src/main.rs
- server/src/metrics/client_metrics.rs
This removes some additional RWLocks that we no longer need
> chore: remove rwlock from validator, client and builder

- server/src/frontend_api.rs
- server/src/openapi.rs
This PR adds `/api/frontend` and `/api/frontend/all` for both POST and GET.
This is done to match the recommended URLs from Unleash server for frontend clients.
We also need to make sure we answer to the /api/frontend/client/register as well, but that's a different PR.
> feat: Added /api/frontend endpoint to match Unleash

- server/src/data_sources/memory_provider.rs
We incorrectly assumed that our merge method would be enough here, but since the merge method retained the original and deduped, it seems like we tricked ourselves. The fix reduces the action to simply replacing whatever was cached with the newly fetched features from the server
Co-authored-by: Simon Hornby <liquidwicked64@gmail.com>
Co-authored-by: Nuno Gois <nuno.gois@getunleash.io>
> fix: Client features were not refreshing.

- server/src/cli.rs
- server/src/client_api.rs
- server/src/http/background_send_metrics.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/metrics/client_metrics.rs
Earlier we didn't accept metrics from downstream clients because we made a wrong assumption about Request Method type. This PR fixes this and starts accepting client metrics and posting them upstream.
There's a PR open on Unleash to make sure ConnectVia on unleash side is also expecting the { appName, instanceId } struct - https://github.com/Unleash/unleash/pull/3213
Closes #80
> fix: Move /api/client/register to a post request.

- README.md
This change moves the edge/proxy comparison section towards the end of
the document (just before the development) section.
The reason is that that section isn't directly about edge and it's
capabilities. I think it makes sense to present what Edge is and how
it works first, and instead present the comparison as extra reading
for people with a special interest.
> docs: move comparison with proxy to the end

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/edge_api.rs
- server/src/http/mod.rs
- server/src/internal_backstage.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/persistence/mod.rs
- server/src/tls.rs
- server/src/types.rs
- server/tarpaulin.toml
Also added some Tarpaulin exclusion arguments to better reflect code coverage across code that we actually want to cover.
There's still some work to do with regards to having the possibility to instantiate the entire application as a test service for full integration/e2e tests, but this at least covers more logic and also exposed a bug in how we validated keys when not using a token validator (offline mode))
> chore: Added tests for edge and client_api

- Cargo.lock
- server/Cargo.toml
- server/src/auth/token_validator.rs
- server/src/builder.rs
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/tokens.rs
- server/src/types.rs
This was unfortunatley the wrong place to have it, it meant we never hit the middleware which validated our token. So unfortunately, we had to make our endpoints depend on the tokencache in order to have the up to date EdgeToken, rather than the one that comes in with the request.
I fear this has broken Offline Mode, so not quite ready to merge just yet
> fix: Move token cache resolution out of FromRequest

- server/src/types.rs
Adds a derive for TokenValidation status with a #[default] on the child enum. This is to prep for the update to Rust 1.68. This is due to an update to Clippy, not Rustc, still compiles on 1.67
> chore: adds a derive for TokenValidation status

- server/src/builder.rs
- server/src/error.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/middleware/validate_token.rs
When a new token for registration comes in, feature refresher registers as a client upstream
We've discussed this before. After talking to Gard and looking at what we were using client registrations for, it made sense for Edge to register as a client for Client tokens that it's fetching data for.
> task: Make Feature refresher register as client

- .github/workflows/release.yml
- Cargo.toml
Updates our rust toolchain to 1.68. This won't build until #103 is merged, due to a new Clippy warning
Edit: Oh. It passes, looks like we're not failing on Clippy warns
> chore: update toolchain to rust 1.68

- server/src/auth/token_validator.rs
- server/src/builder.rs
- server/src/cli.rs
- server/src/error.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/middleware/validate_token.rs
- server/src/persistence/mod.rs
Edge caching tokens could cause tokens to become out of sync with Unleash Upstream, adding a scheduled background task which ensures that our known tokens are still valid will go a long way towards mitigating this.
Discussion point: Should this also reach into the FeatureRefresh cache if it finds an invalid token and remove the FeatureRefresh entry for invalid tokens.
I feel like it should, or rather, I feel like the FeatureRefresher should check status codes and if it receives 403's it should probably remove the token from its own cache.
TokenValidator being aware of the FeatureRefresh and Engine state caches feels like scope creep for the TokenValidator.
> task: Prepare a token revalidator

- README.md
- server/src/error.rs
- server/src/frontend_api.rs
Our client/frontend token separation leads to us having to hydrate client features using a client token. 
If a frontend token comes in that has access to a project/environment combination that Edge has not seen a client token for, this PR now makes Edge consistently return a 511 Network Authentication Required with a body explaining which project and environment the user has to add a client token for.
Using 511 instead of 403 seems more correct, since the token is indeed allowed to access the server, but we haven't yet authorized data upstream.
> task: Return 511 if edge has not hydrated.

- server/src/auth/token_validator.rs
- server/src/types.rs
To make sure we don't hammer upstream with validation requests even if edge is under heavy load, this PR allows Edge to save validation results for invalid tokens as well.
fixes: #119
> fix: Save checked tokens even if invalid

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/error.rs
- server/src/frontend_api.rs
- server/src/http/background_send_metrics.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/metrics/client_metrics.rs
- server/src/prom_metrics.rs
Previously we would save unacknowledged metrics until upstream accepted the post. This PR, splits into 90kB chunks, listens for http status codes to decide what to do on failure.
* 400 will cause us to drop the metrics we tried to post
* 413 would be a surprise, since we already split into chunks to avoid just this
* other status codes will be reinserted to the cache and tried again next minute.
> task: Post appropriately sized metric batches

- README.md
So. Due to bulk metrics not being added to Unleash before 4.22, this adds a note to the doc pointing out that you'll need 4.22 in order for metrics to show up.
The important change is L184-L188, the rest is IntelliJ/VSCode trying to be helpful and formatting my markdown file. I'm very open to suggestions to the phrasing here :)
> docs: Note about Unleash 4.22

- Cargo.lock
- server/Cargo.toml
- server/src/frontend_api.rs
- server/src/types.rs
Currently we do not parse extra parameters into the properties holder for the context. This PR updates edge to make sure that overflows (properties we haven't explicitly defined) get parsed into the properties map
> fix: Fixes incorrect parsing of extra arguments.

- Cargo.lock
- examples/with_custom_constraint.json
- proxyclienttest/app.js
- proxyclienttest/index.html
- server/Cargo.toml
- server/src/error.rs
- server/src/frontend_api.rs
- server/src/lib.rs
- server/src/main.rs
Currently Edge only supports the explicit context variables; properties[key]=value does not work. Since the proxy clients use the `properties[key]` syntax for setting custom context, this PR adds serde-qs for parsing query strings using the `properties[key]=value` syntax.
It also adds a quick proxy-client-js app for verifying that we can set custom context.
fixes: #158
> fix: Building context parameters using map syntax

- .github/workflows/build-docker-release.yaml
We've had requests for unleash-proxy to be pushed to ECR public gallery. So in order to get ahead of possible requests, this pushes to ECR public gallery as well as dockerhub and Github Package Registry.
Already added a separate ecr-public role and added the needed secrets.
> task: added ecr-public login and push target

- server/src/cli.rs
We had forgotten that `:` is a valid part of a header value, so splitting on `:` ended up splitting into too many parts and thus failing the parser. This PR changes to use split_once, which splits on first occurrence. Since Header Names are not allowed to contain `:` this will be fine
> fix: Use split_once.

- README.md
Update the docs to point out that even when running in docker you have to choose which mode you're running in.
> docs: update note about modes and docker

- server/src/http/unleash_client.rs
- server/src/types.rs
Unleash has suddenly started returning token type with uppercase. This PR makes us handle both UPPER and lower case for token type.
The real fix would be for Unleash to obey its own contract with lowercase for token types, but this fix makes us more tolerant to mistakes in Unleash code.
> fix: Handle both upper and lowercase of apitokentype.

- .github/workflows/docker_ecr_arch64.yaml
This is to be more secure and rely on what repo it is rather than a secret to push to ECR
> feat: switch aws auth to oidc

- server/src/builder.rs
- server/src/cli.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
Make sure that upstream certificate and client identity do not depend on each other.
In addition adds more warn and info logging for all upstream communication attempts. Most are added at info!, but the features_fetch call is important enough that we're adding a warn message.
> feat: Add more visible info and warn logging for http errors

- server/src/http/feature_refresher.rs
Turns up the debug output to yield the full response from feature requests. Should be safe but will definitely be noisy
Debugging this is tremendously difficult if something goes wrong here and one of the log outputs is not triggered. This turns this up to 11 so that so long as a request is made and debug output is turned on, you should see __something__
> chore: output logs for any response from feature query in debug output

- server/src/error.rs
Currently, we have no way of knowing why an API request has failed outside of logging. This means that if we miss a log somewhere we have to patch the code in order to understand why it does what it does. This is worse for users because they can't do that and at very best it means fiddling with logging levels to try to figure out what's going on.
This patches the response to include the scrubbed error message as yielded by the `impl Display for EdgeError` implementation. Incoming SDKs will not understand the response here but they will discard the output anyway. Humans, on the other hand, can now understand why a request failed and hopefully how to address it
> chore: allow output from bad requests

- Cargo.lock
- server/Cargo.toml
This bumps Yggdrasil to 0.5.6, which fixes an issue where gradual rollout with a random stickiness would always resolve to false
> chore: bump yggdrasil to pull through fix for rollout not working with random

- server/src/builder.rs
- server/src/http/feature_refresher.rs
- server/src/tokens.rs
Fixes an issue where providing multiple tokens on startup with identical environments and projects would result in no tokens being registered.
This was caused by overeager subsumption of the tokens - identical tokens would subsume each other, and therefore the result of two identical tokens would be no tokens. I've patched this by creating a new list of only tokens that do not have a match for identical project/environment before we do the subsumption.
> fix: allow multiple client tokens at startup

- README.md
- server/README.md
- server/src/cli.rs
- server/src/main.rs
- server/tests/base_path_test.rs
Adds support for a base uri path for the server.
E.g.: `unleash-edge -b nuno edge -t "MY_TOKEN" -u http://localhost:4242`
Will listen on `http://localhost:3063/nuno/api/...`
Closes #190
> feat: add base uri path to server

- Cargo.lock
- server/Cargo.toml
- server/tests/base_path_test.rs
Just an update to types to pull in this fix: https://github.com/Unleash/unleash-types-rs/pull/26
This should make Segments correctly update when a Segment's constraints are changed on the server
> fix: pulls in fixes from Unleash Types so that Segments correctly update

- CLI.md
- Cargo.lock
- server/CHANGELOG.md
- server/Cargo.toml
- server/src/builder.rs
- server/src/cli.rs
In #199 and #200 we discussed that there are instances of Redis where configuring it with a single REDIS_URL variable doesn't make sense. This PR keeps compatibility with previous REDIS_URL configuration, but allows you to use REDIS_HOST, REDIS_USER, REDIS_PASSWORD, REDIS_PORT, REDIS_SCHEME and REDIS_SECURE (overrides scheme and sets it to rediss) to configure Redis as well.
Combinations like REDIS_URL and REDIS_USER and REDIS_PASSWORD is supported. If connecting to REDIS v5 with password you *must* set the REDIS_USER variable to `default`
> feat: add multiple env variables for configuring Redis

- Cargo.lock
- server/Cargo.toml
Update what dependabot wants to do in 6 separate PRs.
> chore: bump versions

- CLI.md
- README.md
- server/README.md
- server/src/cli.rs
Nowhere in the docs it was previously stated how to pass multiple tokens. This documents explicitly that the tokens should be comma separated.
> Document that tokens cli arg allows multiple comma-separated values

- server/src/main.rs
Does what it says on the tin. Not actually sure how this one dodged rustc and Clippy
> chore: remove unneeded import

- Cargo.lock
- server/Cargo.toml
- server/src/frontend_api.rs
Allows Edge to tap into `resolve` in Yggdrasil rather than `resolve_all` when checking a single toggle. This means Edge doesn't have to walk the entire hashmap of state to resolve a single toggle. This provides a modest performance improvement when working with thousands of toggles
> chore: allows resolving a single toggle to do that directly instead of iterating the whole map

- server/src/client_api.rs
- server/src/filters.rs
- server/src/http/feature_refresher.rs
- server/src/lib.rs
- server/src/types.rs
This inverts the way we do filtering of the feature toggles when resolving data out of our cache. Previously we'd materialise the entire response, cloning each. Now we build the filtering at a higher layer and pass the filter in to the method that resolves the toggles. This means that the filter is applied **before** the cloning.
We're a little inefficient with the number of clones we apply when resolving a toggle. This means we stack allocate a **lot** of unnecessary memory. This reduces this to one clone (two on one cold path of retrieving toggles when they're not present in the cache). 
All in all, this doubles the response speed when working with a large number of toggles and halves the memory usage to achieve that.
Summary:
Total:	14.3805 secs
Slowest:	10.0794 secs
Fastest:	0.9730 …
> perf: improve memory usage during request lifecycle

- server/src/filters.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/metrics/client_metrics.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/src/tls.rs
- server/src/tokens.rs
- server/src/types.rs
This narrows the access modifiers for a number of functions and structs that make no sense to be public. This is a nuisance because internal changes become major/minor version changes for no good reason
> chore: reduce unnecessary public api surface

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/frontend_api.rs
This bumps Yggdrasil and UnleashTypes to support strategy variants. This doesn't include test since this is covered by tests in the underlying libraries.
If you're looking for the tests to confirm that metrics work correctly, they're also not here. This is actually handled by the proxy sdks, all Edge does is forward on metrics it receives to Unleash so it's up to the proxy sdk to do this correctly.
> chore: bumps yggdrasil and unleash-types

- CLI.md
- server/src/cli.rs
- server/src/frontend_api.rs
- server/src/http/unleash_client.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/tests/redis_test.rs
So, since the proxy allows you to enable this, to bring Edge to feature parity, this PR allows users to disable the `/api/frontend/all` and `/api/proxy/all` endpoints.
> feat: add disable-all-endpoint flag for disabling proxy /all endpoint

- server/src/cli.rs
- server/src/main.rs
This removes the experimental post features endpoint, this was built for a very particular use case that didn't materialise and this serves no other purpose
> chore: remove experimental post features endpoint

- server/src/http/feature_refresher.rs
- server/src/tokens.rs
Makes the check for incoming front end tokens correctly compare against present tokens so that multiple API calls are not made
> fix: make fe tokens respect token cache

- README.md
- examples/simple-bootstrap.json
- server/src/builder.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/offline/mod.rs
- server/src/offline/offline_hotload.rs
This adds some nice tooling for local development in offline mode. That's two things, firstly the user can now specify a reload interval, which will cause Edge to reload the offline file every X seconds. The second is a simpler format to specify the offline bootstrap in. That's a very, very simplified format, which Edge maps into a full ClientFeatures response matching the expected set properties. Together these allow the user to fiddle with toggles when in offline mode easily so that they can force their SDKs into the states that they want
Almost all of this code does not touch `edge` mode, which is primarily what production environments use. It's also all opt in. So I think this is relatively safe to merge
> feat: add hot reloading and an optional, simpler file format to offline mode

- README.md
Escapes the token format in the docs. This seems to break our documentation generation on Unleash when a fresh build is done
> docs: escapes the token format in the docs

- Cargo.lock
- Cargo.toml
- server/Cargo.toml
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/tokens.rs
- server/src/types.rs
This upgrades Actix Web to 4.4 and Rust TLS to 0.21.
However, I did not do the opentelemetry upgrade, due to the breaking API changes.
> chore: Upgrade to actix 4.4 and rustls 0.21

- Cargo.lock
- Cargo.toml
- server/Cargo.toml
- server/src/internal_backstage.rs
- server/src/tokens.rs
- server/src/types.rs
In order to facilitate debug session, this adds an /internal-backstage/tokens endpoint, which exposes all tokens and the current state that Edge knows about as well as which tokens Edge is refreshing data for.
> feat: added token info endpoint

- server/src/error.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/src/persistence/mod.rs
- server/src/persistence/redis.rs
This adds more output to our error messages when we fail to validate tokens as well as when we receive 401 or 404 from client features endpoints.
> feat: more information in error logs

- server/src/auth/token_validator.rs
- server/src/main.rs
Forces Edge to continue to validate startup tokens until they succeed. This fixes an issue where if Edge couldn't validate the startup tokens against Unleash, it would discard them and never try again. This does make the assumption that Edge should assume the startup tokens are valid and continue to check until it gets a response from Unleash. While the code looks a little icky, the loop becomes a no-op on a background thread once the tokens have been validated and no further calls will occur. If the tokens provided for startup are not valid, Edge will log that in the loop. I think that's correct, since the tokens _should_ be correct, or the user should get a strong warning that the config is broken. If the tokens can be validated during Edge's startup sequence, then the loop will never …
> fix: allow startup tokens to continue to validate against upstream

- server/src/builder.rs
- server/src/cli.rs
- server/src/tokens.rs
Our unreachable code is getting a bit noisy. If we trust rustc and the tests, we should be able to do this without trouble
> small clean ups of unreachable branches

- README.md
- server/src/builder.rs
- server/src/cli.rs
- server/src/error.rs
- server/src/internal_backstage.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/ready_checker.rs
- server/src/tokens.rs
- server/src/types.rs
So, it's nice to have the /internal-backstage/ready endpoint, but since we don't include curl in the docker image, it makes it hard to check ready status when running docker; since both ready and not ready returns 200, we need to parse the body of the response. This PR adds a ready subcommand which does a http request to the /internal-backstage/ready endpoint of a running edge instance.
> feat: Added ready subcommand to cli

- CLI.md
- README.md
- server/README.md
- server/src/cli.rs
- server/src/metrics/client_metrics.rs
fix: Fall back to default 'development' environment value if token does not contain an environment
fixes: #266
fixes: #268
fixes: #162
> fix: Update docs about environment in offline mode

- README.md
This surrounds angle bracketed content in backticks, so that markdown renders it as expected instead of parsing it as html tags. The wrong parsing also causes our doc build to fail.
It currently renders as nothing on github too:
> Quote angle brackets; fix readme

- server/src/client_api.rs
This change fixes a bug where the client API would return all flags
that existed in the cache, even if the api token did not have access
to those flags. Crucially, the API token had to have access to
multiple (but not all) projects for this to happen.
The root cause is that we used the incoming edge token to check which
flags to return. Before it gets validated, its `projects` property is
just an empty list. In the filtering, this causes edge to return all
available. Features.
The solution was to instead use the validated edge token that we
create further up.
There is also a test that confirms this behavior is what we expect.
Could we make it so that the `with_filter` function can only take
validated edge tokens or would that break something else? Might be a
good way to future proof it. …
> fix(#274): use the validated token to calculate flags to return

- server/src/client_api.rs
- server/src/error.rs
- server/src/filters.rs
- server/src/http/feature_refresher.rs
Previously, upon first access with a new token which Edge hadn't seen before our rehydration code only filtered by project of the token, so once it had the data it would stupidly return the token that was available for the new token (in the wrong project).
After this refactor/fix we now apply all filters to all queries for feature toggles from the cache, which should reduce the combinations of possible filter mistakes.
fixes: #276
> fix: No longer return wrong feature toggle

- README.md
- server/README.md
Does what it says on the tin. We've published an article with our best advice for scaling feature flag solutions. This PR adds a link to that article.
> docs: Add link to feature flags best practices

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/persistence/file.rs
Does what it says on the tin, this doesn't alter any features but it does mean client SDKs that support dependent features work correctly against Edge
> chore: bump utoipa and unleash types

- CLI.md
- server/src/cli.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/prom_metrics.rs
- server/src/ready_checker.rs
We've had a customer request to be able to change log formatting. This PR adds support for plain (what we currently have), pretty (a bit friendlier format) and json 
```json
{"timestamp":"2023-11-01T09:00:16.007926Z","level":"DEBUG","fields":{"message":"No update needed. Will update last check time with \"537b2ba0:127766\""},"target":"unleash_edge::http::feature_refresher"}
```
> feat: Add support for setting log format at startup

- server/src/http/feature_refresher.rs
Previously, our cache refresh algorithm assumed that the response from upstream contained all projects we wanted to do updates to. Wayfair correctly reported this breaking their opportunity to archive/delete projects, since the cache would still contain deleted projects.
This patch updates Edge to use the projects the token has access to decide whether or not to keep the elements in cache.
New flow:
1. Fetch projects from token
2. Filter out all features belonging to these projects
3. Extend remaining list with update from response
4. Return extended list.
fixes: #323
> fix: Handle archived/deleted projects

- README.md
Added more explanations of how to use Edge with Redis and debugging. Related to questions from client. ([internal slack thread](https://unleash-internal.slack.com/archives/C05QDP90V9D/p1699260982797929)).
> Docs: debugging and persistent storage explanations

- server/src/http/feature_refresher.rs
Previously our refreshing algorithm assumed that we always had at least one project with an explicit name for deciding what to keep. When in reality we could have a wildcard token (*) for updating. This means that we should just return the update as our new set of data for this token.
Added another test with a wildcard token to verify that we do indeed only keep the update.
In addition, added a filter for unique feature names to what we're keeping to avoid mixing multiple features of the same name.
fixes: #331
> fix: Wildcard token refreshing.

- Cargo.lock
- server/Cargo.toml
This includes the fix for returning a NoneBody rather than a Sized(0) body, allowing the Compress middleware to just not process our response.
Thanks to @phooijenga for the PR on
https://github.com/chriswk/actix-middleware-etag
Fixes: #341
> fix: Update middleware-etag to 0.3.0

- server/src/builder.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/src/tokens.rs
--token-header <TOKEN_HEADER>
Token header to use for both edge authorization and communication with the upstream server [env: TOKEN_HEADER=] [default: Authorization]
This is useful in complex deployment scenarios where proxies are using the Authorization header.
> feat: token-header override

- Cargo.lock
- server/Cargo.toml
- server/src/frontend_api.rs
- server/src/http/feature_refresher.rs
- server/src/main.rs
If upstream goes away, edge should remain durable and keep the features it has gotten for the tokens. Since we already keep the authentication status for the tokens we've seen this fix allows you to start edge, manage to talk to upstream once, then sever connection to upstream, but keep serving feature toggles for known tokens.
There's some superfluous version updates here, just to not have to merge 6 different PRs in addition to this one.
> fix: Do not remove features cache if upstream goes away

- server/src/client_api.rs
- server/src/types.rs
Related to https://github.com/Unleash/unleash/pull/5774 - This adds an X-Edge-Version header to Edge's responses to `/api/client/register`. 
This will allow Edge to compare the version header with the known version where we added `/api/client/metrics/bulk` to decide where to post metrics.
> task: Added version header to client register response

- server/src/builder.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/lib.rs
- server/src/metrics/client_metrics.rs
- server/src/tokens.rs
- server/src/types.rs
- server/src/urls.rs
So, reflecting what we're doing here: https://github.com/Unleash/unleash/pull/5779 this PR adds a client token authenticated endpoint for posting bulk metrics. We also filter the metrics by the environment the token used to POST metrics has access to.
> feat: added client authenticated bulk metrics

- Cargo.lock
- server/Cargo.toml
- server/src/admin_api.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/http/background_send_metrics.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/metrics/client_metrics.rs
- server/src/metrics/mod.rs
- server/src/persistence/file.rs
- server/src/prom_metrics.rs
- server/src/tokens.rs
- server/src/types.rs
- server/tests/redis_test.rs
Will now post to /api/client/metrics/bulk if upstream returns 
- Edge version 17.0.0 or newer.
- Unleash version 5.9.0 or newer (or actually 5.8.0+main, our tip of main).
> feat: Use Version-headers to decide where to post metrics

- Cargo.lock
- server/Cargo.toml
- server/src/builder.rs
- server/src/client_api.rs
- server/src/http/feature_refresher.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/src/offline/offline_hotload.rs
Changes the responses in Edge to include the stickiness property in Strategy Variants.
This technically shouldn't be necessary but this allows us to support versions on our Node SDK that incorrectly use this property for stickiness calculations. 
Note that this PR includes necessary patches to Yggdrasil to handle cases where updating features could fail and previously resulted in crashes in Edge. It's probably useful to review the commit that makes the changes for this patch in isolation: https://github.com/Unleash/unleash-edge/pull/403/commits/ecd3070262b1160a363389686dfce27f62122cf7
> fix: include strategy variant stickiness

- README.md
- examples/docker-compose.yml
A few small clean ups on our docs an examples:
- Removes all the constant versions in our markdown and examples and replaced with version templates or `latest`
- Makes the minimum version of Unleash required clear
- Marks Unleash as `pull_always` in the example compose
> chore: make docker example use up to date edge and unleash versions

- server/src/http/unleash_client.rs
- server/src/metrics/actix_web_metrics.rs
- server/src/prom_metrics.rs
Adds metrics for failed requests.
Closes #412
> feat: add metrics for failed requests

- README.md
Removing this documentation because we want to phase out the usage of this functionality as fast as possible, there will be PRs addressing this code, but this can be merged before that is ready to make it harder to discover functionality we do not recommend to use.
> docs: remove service account token documentation

- Cargo.lock
- server/Cargo.toml
- server/src/builder.rs
- server/src/error.rs
- server/src/frontend_api.rs
- server/src/http/feature_refresher.rs
- server/src/offline/offline_hotload.rs
This upgrades Yggdrasil to a version that's tolerant to all kinds of toggle compile failures. It also makes the frontend/proxy apis return errors rather than panic when resolving toggles that should exist but don't
> fix: degrade broken toggles gracefully in frontend api

- server/src/http/background_send_metrics.rs
- server/src/prom_metrics.rs
Previously we used the previous iteration of the loop's interval to decide next interval. This PR changes to always use the initial send_interval as what to base the interval calculation of
fixes: #436
> fix: make metrics interval not climb forever

- .github/workflows/release.yml
- Cargo.toml
Trying to keep up to date on releases for our release tool. This bumps us to 0.11.1 (most recent at the time of PR)
> chore: updated cargo dist to 0.11.1

- server/src/frontend_api.rs
Update all endpoints of the frontend_api to accept top-level properties.
This is primarily just changing the type we expect and then, on the lower level functions, converting the incoming context into a regular context. 
Most of the functions are pretty straight-forward. `get_all_features` appears to be the only one that doesn't share an implementation with any other functions. 
The tests check:
- `/api/frontend/features/:feature` (`/api/proxy/features/:feature` uses the same impl under the hood, so I've not tested that explicitly. Happy to change that though.
- GET `/api/{frontend,proxy}(/all)?`
- POST `/api/{frontend,proxy)` (POST all features function takes an `IncomingContext` as a parameter, so I'm assuming the serialization here works; can of course add tests for that too)
- That …
> fix: handle incoming requests on the api level

- README.md
- server/README.md
This change updates the readmes with the right dependencies for 18.0.1
> chore: prepare for readmes for release

- README.md
- server/src/auth/token_validator.rs
- server/src/edge_api.rs
- server/src/http/background_send_metrics.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/openapi.rs
- server/src/persistence/file.rs
- server/src/types.rs
We no longer want /edge/metrics to be available, since we have released 17.0.0, 17.1.0, 18.0.0 and 18.0.1 with compatibility for both `/edge/metrics` and `/api/client/metrics/bulk` this PR now strips the old endpoint in preparation for releasing 19.0.0. After this is released, you will need at least Unleash 5.9.0 to get metrics from Edge.
> fix: Removed /edge/metrics and logic for posting to /edge/metrics

- Cargo.lock
- server/Cargo.toml
This fixes an issue where the `impression_data` field would not be correctly camelCased on front-end responses
Done via a bump in unleash types. Yggdrasil gets a bump too since that has a dependency on types and needs this to compile correctly
> fix: bump unleash types so that impression data is correctly camelcased

- server/src/auth/token_validator.rs
- server/src/builder.rs
- server/src/edge_api.rs
- server/src/error.rs
- server/src/http/background_send_metrics.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/internal_backstage.rs
- server/src/openapi.rs
- server/src/ready_checker.rs
- server/src/tokens.rs
- server/src/types.rs
Previously, if the update was empty, we assumed we needed to replace all stored features. This is not the case. We only need to remove the projects that are connected to the token we're using for the merge.
In addition, debug output on `/internal-backstage/tokens` now includes how many features was received in the update
> fix: Only replace projects covered by token

- README.md
Adds some recommendations around startup parameters that should result in healthy running of Edge for most circumstances
> docs: add startup configuration recommendations

- server/src/builder.rs
- server/src/cli.rs
https://linear.app/unleash/issue/2-2385/add-deprecation-logs-to-dynamic-behavior
Adds deprecation logs for dynamic behavior.
This should cover phase 1 of our [migration plan](https://linear.app/unleash/document/migration-plan-b3d7f35abc4e)
No explicit behavior:
Explicitly dynamic:
Explicitly strict:
> chore: add deprecation logs for dynamic behavior

- README.md
- docs/benchmarking.md
- docs/concepts.md
- docs/deploying.md
- migration-guide.md
- server/README.md
Start of the work with regards to making our README the one-stop shop to understand how to run Edge. Moving deployment, concepts, migration and other details into separate files to keep README concise and easy to read.
> docs: Make README a quickstart and move concept/benchmarking/deploying to separate files

- server/Cargo.toml
- server/src/builder.rs
- server/src/cli.rs
- server/src/persistence/redis.rs
- server/tests/redis_test.rs
Previously, if you gave us a redis url that was valid, but used the wrong protocol (so rediss when connecting to insecure, or redis when connecting to secure), operations against Redis got stuck. This PR adds a timeout setting (setting it to default of 2000 ms, but configurable).
This does add time when url is completely invalid (i.e. there's nothing listening), but it prevents the client from getting stuck indefinitely if something answers, but redis can't get an answer.
> fix: add timeout for redis read and write ops.

- Dockerfile.publish
> fix: Update docker image to use the nonroot tag of distroless

- README.md
- server/README.md
- Added Prometheus endpoint
- Added table of contents (let's discuss if we want this)
- Added overview and extend the initial description
- Reorganize headings (moved links to external pages to the bottom)
- Standardize formatting for placeholders
- Reworded some sections to improve clarity 
- Applied preferred formatting for availability
- Reworded 'deprecation' around dynamic mode, and encouraged the use of strict mode throughout
- Removed redundant troubleshooting section
**[Preview the readme](https://github.com/Unleash/unleash-edge/blob/3dd5eb7b9e17582dec1639420829faae82dc5f9d/README.md)**
TO-DO:
> Restructure readme

- README.md
- server/README.md
Minor wording fix to avoid confusion between docker tag and command
> Update instruction to refer to docker command not tag

- README.md
- docs/deploying.md
When debugging, it might be useful to check tokens and features endpoints
> docs: add additional details for debugging

- README.md
A recent docs change on Edge [broke the docs build](https://github.com/Unleash/unleash/actions/runs/10737877321/job/29781703218?pr=8050). This PR fixes the formatting.
[Markdown deeplink to Debugging section](https://github.com/Unleash/unleash/actions/runs/10737877321/job/29781703218?pr=8050).
> Fix formatting to avoid JSX rendering bug

- server/src/persistence/redis.rs
Work around for Rust 2024 implementing Never type (!)
https://github.com/rust-lang/rust/issues/123748
> fix: Update to explicitly type RedisError.

- server/src/metrics/client_metrics.rs
- server/src/prom_metrics.rs
This exposes the feature usage metrics Edge receives (and sends upstream). We might want to add a caveat in the docs that you shouldn't aggregate both Edge and Unleash data (Edge aggregates for you and sends upstream)
fixes: https://github.com/Unleash/unleash-edge/issues/469
> feat: added feature_toggle_usage_total counter

- server/src/persistence/s3.rs
- server/tests/s3_tests.rs
Having the creation like this breaks buckets in regions other than us-east-1
> fix: remove bucket creation in s3 persister

- server/src/frontend_api.rs
Moves the all endpoints for the frontend API to use the same context parsing path as the non all endpoints. Fixes an issue where context properties would not be correctly considered in the feature evaluation
Closes #555
> fix: frontend all endpoints now accept context correctly

- server/src/http/background_send_metrics.rs
- server/src/main.rs
Flushes metrics to upstream on shutdown. Needs a bit of love and/or discussion before merge:
1) Be cool if this was tested by the same things that test the standard metrics send but I don't see those tests (currently tested by humans)
2) Is 5 parameters to a function too much? It feels like too much
> feat: flush metrics on clean shutdown

- CLI.md
- Cargo.lock
- server/Cargo.toml
- server/src/cli.rs
- server/src/internal_backstage.rs
- server/src/main.rs
- server/src/metrics/metrics_pusher.rs
Sensitive endpoint (tokens, features, metricsbatch, metrics) can now all be turned off with separate flags
Co-authored-by: Simon Hornby <liquidwicked64@gmail.com>
> feat: internal-backstage endpoints are disableable.

- server/src/builder.rs
From conversations with customers, if you feed edge with invalid tokens in strict mode, edge will quietly reject the invalid tokens, but the initial check that we actually had tokens will succeed, so will happily continue running after rejecting the tokens.
This PR checks that have valid tokens after validating tokens on startup.
> fix: added error if no tokens are valid when starting in strict mode

- server/src/builder.rs
- server/src/http/unleash_client.rs
- server/src/internal_backstage.rs
- server/src/middleware/validate_token.rs
- server/src/offline/offline_hotload.rs
After adding support for client and frontend tokens, we did not extend the reloader to check client and frontend token Vecs, this PR extends tokens with FE and Client tokens, to ensure that we refresh the data for all our tokens.
In addition we make /internal-backstage/tokens useful for offline mode as well, to at least be able to see which tokens you added to Edge.
In addition, since offline mode did not set up a token validator, I extended the auth middleware to check if our offline token has a token type set and if they do, limit their access to what they were intended for (client for /api/client, frontend for /api/frontend | /api/proxy)
Fixes: #594
> fix: bootstrap reload in offline mode.

- Cargo.lock
- server/Cargo.toml
- server/src/metrics/actix_web_metrics.rs
So. Finally opentelemetry prometheus updated to 0.27, so we can move on from 0.24.
This PR updates all opentelemetry dependencies to 0.27.
> fix: bump opentelemetry dependencies to 0.27

- .github/workflows/test-with-coverage.yaml
- server/src/builder.rs
- server/src/client_api.rs
- server/src/feature_cache.rs
- server/src/frontend_api.rs
- server/src/http/broadcaster.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/internal_backstage.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/src/offline/offline_hotload.rs
- server/src/persistence/mod.rs
- server/src/ready_checker.rs
- server/tests/streaming_test.rs
Added tokio broadcast channel for pushing updates to SSE subscribers.
> feat: broadcast updates

- README.md
- server/README.md
Unleash edge does not keep feature parity with unleash-server. Despite most of the features are currently supported, some are not and we don't have plans to support them.
Closes #601
> docs: notice about feature parity with unleash-server

- server/src/client_api.rs
- server/src/error.rs
- server/src/http/broadcaster.rs
This PR stops up a couple shortcuts taken for the initial streaming implementation in edge.
Mostly just returns better errors where possible.
> chore(1-3211): handle minor edge cases for errors

- server/src/http/feature_refresher.rs
- server/src/http/headers.rs
- server/src/http/mod.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
This pr adds the same headers to the streaming clients as we use for polling clients.
> chore(1-3216): send the same headers in streaming as for polling

- server/src/http/feature_refresher.rs
Instead of using `while let Ok(...)` To run the listening loop, we'll just use a plain old loop. This is an experiment to see if this'll make it always reconnect succesfully.
> chore(1-3217): run SSE listener in infinite loop

- server/src/client_api.rs
- server/src/http/broadcaster.rs
This PR refactors the broadcaster and what it stores per client:
- I've created a new StreamingQuery struct that has only the data we need,
- I've moved the token storing from client group level to individual client level (and created a ClientData struct)
I realized when setting up the tests for this that the Query, EdgeToken, and FilterQuery all contain more or less the same bits of data. But all we really need is:
1. The actual token string (so that we can boot clients if the token expires)
2. Name prefix, projects, and env.
In the Unleash Types `Query` type, projects and env are optional, but we need them to be present to perform the calculation.
So I created a `StreamingQuery` struct, which consolidates the data we need from the Query and EdgeToken. I also copied in the methods we use …
> refactor: store less information per streaming client

- server/src/http/broadcaster.rs
This PR updates the broadcaster to only push updates to listeners in the environment it got updates for. In other words, if you get an update for "development" config, you shouldn't push an update to listeners subscribed to the "production" environment.
This is the first step in more selective pushing (the next would be to do as we do in Unleash and hash the result of each query so that we only push out updates when something's actually changed).
> feat(1-3220): only push updates to listeners in the same environment

- Cargo.lock
- examples/hostedexample.json
- server/Cargo.toml
- server/src/client_api.rs
- server/src/feature_cache.rs
- server/src/filters.rs
- server/src/frontend_api.rs
- server/src/http/broadcaster.rs
- server/src/http/unleash_client.rs
- server/src/internal_backstage.rs
- server/src/offline/offline_hotload.rs
- server/src/persistence/file.rs
- server/src/ready_checker.rs
- server/src/types.rs
- server/tests/redis_test.rs
- server/tests/s3_tests.rs
- server/tests/streaming_test.rs
Trying to get tip of main working, but some tests are failing.
I suspect it is related to the new meta field, I added it to all obvious places, but I think its more complex.
> fix: add meta to support new format

- server/src/filters.rs
- server/src/http/broadcaster.rs
This PR performs a small amount of cleanup after #618 based on the PR discussion. Specifically, it:
- Adds a new `project_filter_from_projects` function to the filters file, and makes `project_filter` fall back to that on the back end (we can discuss the names here, but doing it this way saved me touching any more code)
- Reverts the `std::mem::take` shenanigans in favor of cloning. Even though it clones one string per attached listener every 30 seconds, it's probably not going to cause a lot of memory overhead given that we drop the original shortly thereafter.
> refactor: minor cleanup after #618

- Cargo.lock
- server/Cargo.toml
- server/build.rs
Update dependencies in bulk, we're moving to dependabot and mergify instead of renovate bot, which allows us to merge dependency updates once approved and building.
> chore: Bulk upgrade dependencies

- server/src/builder.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/http/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/middleware/client_token_from_frontend_token.rs
> feat: start using instance_id argument for instance_id header

- server/src/cli.rs
- server/src/main.rs
I had a conversation on Slack today, and Edge's keepalive came up. This PR makes it configurable, but still uses the same default that we already had in place of 5 seconds.
> feat: Make keep alive timeout configurable (still default to 5 seconds)

- server/src/cli.rs
Align delta with streaming, only to work in strict mode and not conflicting.
We are not supporting legacy dynamic mode.
> feat: make delta aligned with streaming, support only strict

- server/src/client_api.rs
- server/src/error.rs
- server/tests/streaming_test.rs
Make it so that the /streaming endpoint only accepts connections if the server is in streaming mode. This effectively renders the /streaming endpoint useless if the server is not connected to an upstream stream.
This first solution uses the 403 http status code and tells the user that the endpoint is only enabled in streaming mode.
Is there a way to not mount this if we're not streaming? Is introducing a new edge error the right thing to do here, or is there an easier way to return arbitrary status codes?
> chore(1-3244): only expose streaming endpoint if in streaming mode

- Cargo.lock
- server/Cargo.toml
- server/src/feature_cache.rs
- server/src/http/refresher/delta_refresher.rs
- server/src/http/refresher/feature_refresher.rs
Make edge support the new delta format.
> feat: update edge to new delta format

- server/src/cli.rs
- server/src/main.rs
Reported in #701 - Edge currently is set to Allow-Any-Origin  (`*`). the Issue requests the possibility to lock it down more than this.
This PR uses the same configuration variables available in Unleash Proxy: https://docs.getunleash.io/reference/unleash-proxy#configuration-options but excludes the ones that are not supported by our actix-cors middleware.
fixes #701
> feat: add configuration possibilities for CORS middleware

- Cargo.lock
- server/Cargo.toml
- server/src/delta_cache.rs
- server/src/lib.rs
Edge needs to start keeping all the deltas in cache. This is a cache where these deltas are kept. Tried to keep it consistant with delta cache inside Unleash https://github.com/Unleash/unleash/blob/4a72580b2477c91883680fd03adc8e31ef85f48f/src/lib/features/client-feature-toggles/delta/delta-cache.ts#L7.
> feat: implement delta cache in edge

- server/src/cli.rs
Hides the CLI flags for delta, delta_diff and streaming. This means consumers of the compiled binary won't be able to see these at all. To find the flag you need to read the source and that takes you face to face with the warning about depending on these features
> chore: hides flags for detla, delta_diff and streaming

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/delta_cache.rs
- server/src/delta_filters.rs
- server/src/filters.rs
- server/src/http/refresher/delta_refresher.rs
- server/src/http/refresher/feature_refresher.rs
- server/src/lib.rs
- server/src/main.rs
This PR handles 2 things
1. Etag handling, so we know what etag we receiving and what to send back
2. Filtering features based on etag and query params
Next PR
1. Automatic tests for client API.
2. Connect to delta cache manager, which is also being developed currently.
> feat: delta filtering and etag handling

- server/src/client_api.rs
- server/src/delta_filters.rs
We were not filtering segment events by revision so for segment events we were getting extra events
> fix: filter segment events by revision

- CLI.md
- Cargo.lock
- server/Cargo.toml
- server/src/cli.rs
- server/src/main.rs
Uses https://github.com/Unleash/actix-allow-deny-middleware to configure an allow- and a deny-list for access to the server. By default configures the allow list to allow all IPs and the deny list to be empty (deny no IPs).
> feat: add allow-list and deny-list middlewares

- server/src/metrics/actix_web_prometheus_metrics.rs
Inadvertently forgot that we were using milliseconds, not seconds in the old middleware. This PR reverts back to using milliseconds rather than seconds for request durations.
> fix: actix prometheus metrics should also report in milliseconds

- examples/frontend-stable-sort.json
- server/src/frontend_api.rs
With a great example in #797 for why they get 200 on their frontend.
We figured out that we didn't have a stable sort for our feature flags with the frontend API. 
This PR adds sorted_by_key to the list of frontend_results and a test to verify that we get 304 for multiple requests, removing the sorted_by_key causes the test to fail. 
fixes #797
> fix: make sure we sort the list of frontend results by feature name

- server/src/metrics/actix_web_prometheus_metrics.rs
With a publicly available URL we should redact path for any status code that did not yield success.
> fix: redact path to /{unknown} if status is not success

- docs/CLI.md
Fixing a pair of unescaped < and > in CLI.md. Without code formatting, they are treated as the start and end of HTML tags and break the rendering. The MDX parser is also unhappy and throws an error in the docs.
> docs: fix formatting issue in cli.md

- docs/migration-guide.md
Fix another small formatting issue that the MDX parser is unhappy about.
> docs: fix formatting in migration-guide

- server/Cargo.toml
- server/src/builder.rs
- server/src/persistence/s3.rs
- server/tests/s3_tests.rs
Moves the S3 persister behind a flag so we can optionally not compile the AWS SDK stuff because it's really really heavy. This lets us run builds with --no-default-features. That's about 30-40% faster
Left this on by default so it's opt out
> chore: move s3 persistence behind flag

- server/src/auth/token_validator.rs
- server/src/middleware/validate_token.rs
- server/src/tokens.rs
- server/src/types.rs
- server/tests/streaming_test.rs
Adds a pathway to create trusted tokens in Unleash Edge. These tokens are allowed to entirely skip validation so you can have tokens that look like "haha-I'm-totally-a-valid-token-bro-trust-me". This PR does nothing on its own, it's purely the plumbing layer but this allows us to inject these tokens on startup (coming in a future PR) into the cache and use Proxy style tokens
> chore: trusted token plumbing

- server/src/cli.rs
Before this patch, instance-id arg had to come before subcommands `edge | offline`. With this patch, instance-id is now a global argument and come anywhere in the launch command.
fixes #913
> fix: make instance-id cli arg a global argument

- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/http/refresher/feature_refresher.rs
- server/src/metrics/client_metrics.rs
After this change all frontend and backend apps reported in bulk metrics to Unleash will have a list of projects attached to them so that we can report more than '*' in Unleash itself.
The new projects field on the ClientApplication is Optional vector of projects. The reason for that is because same type is used for SDKs sending data to Edge and Edge sending data to Unleash. SDKs don't provide projects in the ClientApplication but in the token. However Edge sends bulk application data to Unleash so it has to provide projects on the ClientApplication itself.
> feat: client application projects

- .github/workflows/clippy.yaml
- Cargo.lock
- server/Cargo.toml
- server/src/client_api.rs
- server/src/frontend_api.rs
- server/src/metrics/client_metrics.rs
- server/src/metrics/edge_metrics.rs
- server/src/tokens.rs
- server/tests/streaming_test.rs
As a security upgrade, this PR updates prometheus to 0.14.0 which bumps protobuf to fix https://github.com/Unleash/unleash-edge/security/dependabot/27
> chore(deps): Updated prometheus to 0.14.0

- docs/CLI.md
- server/src/builder.rs
- server/src/cli.rs
- server/src/client_api.rs
- server/src/http/instance_data.rs
- server/src/main.rs
- server/src/tokens.rs
- server/tests/streaming_test.rs
We have customers running behind ServiceMeshes, firewalls, API gateways that occupy the Authorization header with their authorization setup. This PR splits Edge's headers into two
- --edge-auth-header - Which header should be used to authorize access to your Edge instance
- --upstream-auth-header - Which header should Edge use to authorize against the upstream instance (typically Unleash, but in daisy-chain cases, can be another Edge, which should then make sure upstream's `--edge-auth-header` matches downstream's `--upstream-auth-header`)
> feat: Added --edge-auth-header and --upstream-auth-header args

- .config/cargo.toml
- docs/development-guide.md
- justfile
Provides a setup for a better build + test loop. This uses  [Cranelift](https://cranelift.dev/) and [LLD](https://lld.llvm.org/) to get a faster compile and skips the build + test for the integration tests. This improves the time for build + test on a hot compile from about 55 seconds to about 8 seconds on my machine. 
This is entirely opt in, so standard `cargo build` will still use the old tool chain and release builds are unaffected.
This doesn't use [Mold](https://github.com/rui314/mold), since that has some iffy support on MacOS/Windows
> chore: better dx

- docs/development-guide.md
- justfile
Few small maintenance things for the just build
- Passes through options to the test runner so it works the same as `cargo test`, this lets you target single tests or enable features, etc.
- Adds two new just tasks that will use the default system linker instead, which is friendlier for folks who cannot use LLD
- Updates the dev docs
> chore: add in build configs for when lld won't work

- server/src/builder.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/metrics/client_impact_metrics.rs
- server/src/metrics/edge_metrics.rs
- server/src/metrics/metric_batching.rs
- server/src/middleware/consumption.rs
- server/src/prom_metrics.rs
Extracted and refactored Actix app initialization into a dedicated setup_server function. This change removes inline setup logic from main.rs, reduces duplication, and centralizes App configuration. Mostly it makes it saner to read and reduces the 300 line main to a bunch of smaller functions that limit the amount of state sharing.
No functional changes. All runtime behavior, endpoints, and tasks remain identical.
> refactor: clean up main

- server/src/builder.rs
- server/src/cli.rs
- server/src/http/refresher/feature_refresher.rs
- server/src/http/unleash_client.rs
- server/src/main.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/tests/streaming_test.rs
Adds an option for setting keep alive timeout for connections between Edge and upstream. Defaults this to Unleash's interval - 15 seconds.
Also does a bunch of surgery to fix tests :cry:
> feat: add an option for setting upstream keep alive timeout

- server/src/auth/token_validator.rs
- server/src/builder.rs
- server/src/client_api.rs
- server/src/edge_api.rs
- server/src/internal_backstage.rs
- server/src/lib.rs
- server/src/middleware/client_token_from_frontend_token.rs
- server/tests/streaming_test.rs
This does nothing useful, it just adds a constructor function to the token validator so that we can make some invasive internal changes without touching the entire application
> chore: add a constructor to token validator

- benchmarks/clientfeaturesendpoint.js
- benchmarks/keyrotation_benchmark.js
- server/src/error.rs
- server/src/http/unleash_client.rs
So, previously we forced all failed TokenValidationErrors to return Bad Data. This PR instead returns the status code that came from the upstream validation.
This means, if upstream is telling us 429, Edge will also tell downstream 429 (Too many requests).
We don't often get these errors, but we some suspicion that a certain customer's 400s is due to this.
> fix: validation error should reflect status code

- crates/unleash-edge-http-client/src/instance_data.rs
- crates/unleash-edge-metrics/src/metrics_pusher.rs
- crates/unleash-edge-types/src/metrics/instance_data.rs
- crates/unleash-edge/src/edge_builder.rs
- crates/unleash-edge/src/lib.rs
So, I was struggling with getting observability reporting to work. Turned out since we used the register_<metric_type> macros they got registered with the default registry. And I checked the code, our old custom registry that only loaded process metrics if running on linux os is already part of the default registry if you enable the process feature. No need to create a custom registry to have those.
This PR removes custom registries and uses the default one for everything.
> fix(metrics): Edge observability now works

- Cargo.lock
- crates/unleash-edge-delta/Cargo.toml
- crates/unleash-edge-delta/src/cache_manager.rs
- crates/unleash-edge-http-client/src/instance_data.rs
- crates/unleash-edge-integration-tests/src/feature_refresher.rs
- crates/unleash-edge-integration-tests/src/streaming_refresher.rs
- crates/unleash-edge-integration-tests/src/token_validator.rs
- crates/unleash-edge-persistence/src/file.rs
- crates/unleash-edge-types/src/lib.rs
- crates/unleash-edge-types/src/metrics/instance_data.rs
- crates/unleash-edge-types/src/tokens.rs
- crates/unleash-edge/src/edge_builder.rs
- crates/unleash-edge/src/middleware/validate_token.rs
- crates/unleash-edge/src/offline_builder.rs
- One that counts live connections, updated on each event being sent out.
- One that counts connections made, incremented on each connection
In addition this PR adds a shutdown task for our DeltaCacheManager, sending a
PoisonPill in the form of a Delete message.
> feat: count connected streaming clients

- crates/unleash-edge-cli/src/lib.rs
https://linear.app/unleash/issue/2-3886/allow-explicit-cors-origin-in-edge
Allows explicit `*` in CORS origin.
This should make CORS configuration more intuitive, as users can now safely specify `*` for origins without crashing on startup.
Includes some scouting.
Related: https://github.com/Unleash/unleash-edge/issues/1167
> feat: allow explicit * in CORS origin

- crates/unleash-edge-integration-tests/src/streaming_refresher.rs
- crates/unleash-edge-streaming/src/stream_broadcast.rs
Stops the streaming implementation from sending updates to all environments rather than just the environment that the client is connected to
> fix: streaming duplication

- Cargo.toml
- crates/unleash-edge/src/lib.rs
- crates/unleash-edge/src/main.rs
- crates/unleash-edge/src/middleware/validate_token.rs
since it's the thing we use if you happen to terminate TLS, it makes sense to use it when only hosting http as well.
> experiment: Use axum_server instead of axum::serve
